runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: lxml
  version: latest

automatic_scaling:
  max_instances: 1

handlers:
- url: /.*
  script: handlers.index.app
